# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iterate <- function(Y, df_j, nrep, n, d, gamma, q, init, mu0, lambda0, alpha, beta) {
    .Call(`_BayesSpace_iterate`, Y, df_j, nrep, n, d, gamma, q, init, mu0, lambda0, alpha, beta)
}

iterate_vvv <- function(Y, df_j, nrep, n, d, gamma, q, init, mu0, lambda0, alpha, beta) {
    .Call(`_BayesSpace_iterate_vvv`, Y, df_j, nrep, n, d, gamma, q, init, mu0, lambda0, alpha, beta)
}

iterate_t <- function(Y, df_j, nrep, n, d, gamma, q, init, mu0, lambda0, alpha, beta) {
    .Call(`_BayesSpace_iterate_t`, Y, df_j, nrep, n, d, gamma, q, init, mu0, lambda0, alpha, beta)
}

iterate_t_vvv <- function(Y, df_j, nrep, n, d, gamma, q, init, mu0, lambda0, alpha, beta) {
    .Call(`_BayesSpace_iterate_t_vvv`, Y, df_j, nrep, n, d, gamma, q, init, mu0, lambda0, alpha, beta)
}

cluster_mcmc <- function(Y, df_j, nrep, gamma, q, init, mu0, lambda0, alpha, beta) {
    .Call(`_BayesSpace_cluster_mcmc`, Y, df_j, nrep, gamma, q, init, mu0, lambda0, alpha, beta)
}

iterate_t_orig <- function(Y, df_j, nrep, n, d, gamma, q, init, mu0, lambda0, alpha, beta) {
    .Call(`_BayesSpace_iterate_t_orig`, Y, df_j, nrep, n, d, gamma, q, init, mu0, lambda0, alpha, beta)
}

iterate_t_refactor <- function(Y, df_j, nrep, n, d, gamma, q, init, mu0, lambda0, alpha, beta) {
    .Call(`_BayesSpace_iterate_t_refactor`, Y, df_j, nrep, n, d, gamma, q, init, mu0, lambda0, alpha, beta)
}

iterate_deconv <- function(Y, df_j, tdist, nrep, n, n0, d, gamma, q, init, subspots, verbose, jitter_scale, c, mu0, lambda0, alpha, beta) {
    .Call(`_BayesSpace_iterate_deconv`, Y, df_j, tdist, nrep, n, n0, d, gamma, q, init, subspots, verbose, jitter_scale, c, mu0, lambda0, alpha, beta)
}

dmvnorm_arma <- function(x, mean, sigma, logd) {
    .Call(`_BayesSpace_dmvnorm_arma`, x, mean, sigma, logd)
}

dmvnrm_arma <- function(x, mean, sigma, logd) {
    .Call(`_BayesSpace_dmvnrm_arma`, x, mean, sigma, logd)
}

dmvnrm_arma_fast <- function(x, mean, sigma, logd) {
    .Call(`_BayesSpace_dmvnrm_arma_fast`, x, mean, sigma, logd)
}

start_profiler <- function(str) {
    .Call(`_BayesSpace_start_profiler`, str)
}

stop_profiler <- function() {
    .Call(`_BayesSpace_stop_profiler`)
}

